
clients:
  - url: http://localhost:4100/loki/api/v1/push   # Make sure this port matches your Loki http port
    backoff_config:
      max_period: 5s    # Keep retries short such that terminal is still usable if Loki is unavailable
      max_retries: 3

scrape_configs:
- job_name: system
  static_configs:
  - labels:
      job: shell  # We are using the --stdin flag so logs come from stdin, this flag uses the first defined scrape config
                  # which is this config, set a label job=shell
